version: '3.8'

services:
  tictactoe:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
