[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "dist/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist/public"

[[redirects]]
  from = "/ws/*"
  to = "/.netlify/functions/websocket/:splat"
  status = 200
  force = true
  conditions = { Upgrade = "websocket" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 